### PR TITLE
Support Grape Api

### PR DESCRIPTION
**Pull request by phuongnd08**
Grape is also a popular option to write API with Rails. This PR add out of the box support for app that use grape (https://github.com/ruby-grape/grape)

### CODE REVIEW

**Comment by mgomes** [comment]
@phuongnd08 thanks for this PR. I think Grape support would be welcomed by a lot of people. Could you add some test coverage for this driver? There are few other drivers you could use as a reference.

**Comment by dunghuynh** [comment]
@mgomes, I have added test for this driver and merged to master. However, the master branch build is failed.
The test passed in my local development with rails_51.gemfile

**Comment by mgomes** [comment]
@dunghuynh thank you. @fwininger did some work to clean up the test suite on master. We just merged those changes in... Could you please merge master in again and see if that does the trick? 🙏

**Comment by phuongnd08** [comment]
@fwininger All tests has passed now.

**Pull request merged**
