### PR TITLE
Fix unit tests pipeline and drop support for Ruby < 2.3

### PR DESCRIPTION
**Pull request by fwininger**
Clean some code to fix the unit test pipeline.

According https://www.ruby-lang.org/en/downloads/branches/ I suggest to drop the support of Ruby < 2.3.

Please accept this PR to move forward !

### CODE REVIEW

**Comment by fwininger** [comment]
The gem http also drop the support of ruby < 2.3 (https://github.com/httprb/http)

**Comment by fwininger** [comment]
@mgomes can you merge this please ?

**Comment by mgomes** [comment]
@fwininger thanks for this! Do you think we consider dropping support for Rails < 4.2 in the near future as well?

**Comment by fwininger** [comment]
@mgomes : thanks for this quick review. I agree to drop the support for Rails < 4.2 (like the Rails Team), but I suggest to drop the support only when it cause some troubles for this PR, like Ruby actually.

**Pull request merged**
