### PR TITLE
Add support for Typhoeus

### PR DESCRIPTION
**Pull request by nathanhoel**
Typhoeus performs parallel http requests (https://github.com/typhoeus/typhoeus)

### CODE REVIEW

**Comment by nathanhoel** [comment]
I made changes to the gemfile to do this which I noticed that travis does not like. If there are things you'd like me to change about this let me know and I can work with you, we would love to point our app back to the main api_auth gem instead of our own.

**Comment by kjg** [comment]
Thanks so much for this! The reason Travis is complaining it due to all the Gemfiles in the gemfiles folder that we use to test against different ruby versions.

Please run `bundle exec rake appraisal:gemfiles` And this should update all those lock files as well.

What's the reason for the test-unit dependency?

**Comment by nathanhoel** [comment]
That makes sense. I did notice those gemspecs. I can do that.

Test-unit gem was to support newer versions of rails, some of the test stuff has been removed from newer versions of active support I believe (going off memory). I should remove that and leave that for a separate pull request for someone else.

**Comment by nathanhoel** [comment]
So I removed the unnecessary gemfile changes and I updated the appraisal gemspecs.locks, however some of them keep failing randomly. By randomly I mean I made a few unrelated commits (didn't change the gemspecs) and then some that were failing would pass and others that were passing would fail.

**Comment by kjg** [comment]
i've found the root cause of the random failures.

It is because the date header is being set via two different capitalizations. [`'date' => Time.now.utc.httpdate`](https://github.com/mgomes/api_auth/pull/63/files#diff-3127589ed254f361c3629d8e63ac806bR575) in the `before(:each)` vs  [`@request.options[:headers]['Date'] = 16.minutes.ago.utc.httpdate` and `@request.options[:headers]['Date'] = "٢٠١٤-٠٩-٠٨ ١٦:٣١:١٤ +٠٣٠٠"`](https://github.com/mgomes/api_auth/pull/63/files#diff-3127589ed254f361c3629d8e63ac806bR634) in the specific examples that randomly fail.

When [`capitalize_keys`](https://github.com/nathanhoel/api_auth/blob/1a882131df77c05b019bc45a3970912a260e54b9/lib/api_auth/helpers.rb#L23) is called in the headers, it's just a matter of "luck" which version of date ends up being the final 'DATE'.

**Comment by nathanhoel** [comment]
I copied the test from the httpi tests, interesting that they do not suffer from the same issue. the 'luck' may be a timing issue that is only occurring for Typhoeus.

I can fix this in my next commit.

**Comment by kjg** [comment]
HTTPI uses [Rack::Utils::HeaderHash](http://www.rubydoc.info/github/rack/rack/Rack/Utils/HeaderHash) which is described as "A case-insensitive Hash that preserves the original case of a header when set." Whereas typhoeus is using just a normal ruby hash for their header storage

**Comment by kjg** [comment]
Closing this in favor of #64

**Pull request closed without merging**
