### PR TITLE
Add HMAC_DATE header for ajax request

### PR DESCRIPTION
**Pull request by andres99x**
I was working on an Angular project and i had trouble with the DATE header. It seams that for security reasons it can't be modified on ajax requests.

Because of this i had to add another posible header for the date, named: "HMAC_DATE"

I also did a bower package to be used with Angular that plays nicely with your gem.

Bower package: https://github.com/andres99x/angular-hmac-auth

I hope you are ok to merge the PR so people can start using your gem with my package. :)

### CODE REVIEW

**Comment by kjg** [comment]
Thanks for doing this! Can you please use `X_HMAC_DATE instead as I think that would conform better to prefixing non-standard headers with an X.

What happens if the request has both DATE and X-HMAC-DATE headers? Should the X-HMAC-DATE one be preferred for the calculations?

Also, can you please add some specs around this and docs to make this new feature easily discoverable for others?

Thanks again!

**Comment by andres99x** [comment]
Great suggestions! and i believe X-HMAC-DATE should be preferred over DATE.

I'll try and get this done over the weekend :+1:

Glad you liked it!

**Comment by andres99x** [comment]
@kjg I got too exited about this that i couldn't wait for the weekend.

While working with the gem i noticed a lot of repetitive code that i tried to encapsulate in order to DRY it up. You will notice i created a RequestDriver::Base clase where i put all the drivers shared behaviour.

I also removed a lot of code from the ApiAuth::Headers class, delegating some of it's methods directly to the ```@request``` object.

Regarding the tests, i added the ones needed as you suggested in order to tests the new headers and their precedence,  also i fixed a couple of them that were not properly testing the behaviour.

I know i did change a lot of code, i hope you are okey with these changes and you agree to merge.

If you have any questions please feel free to ask.

**Comment by kjg** [comment]
This looks really good to me. Thanks so much for doing all this!. Because of the scope of the refactoring I'd like @mgomes to weigh in as well.

Are X_HMAC_CONTENT_MD5, X_HMAC_CONTENT_TYPE, and X_HMAC_AUTHORIZATION needed? I understand the DATE issues as I've run into it as well, does the same issue occur with these other headers?

I understand why you changed md5_mismatch to md5_match since it is often preferable to use positive terminology instead of negative. However the reason I went negative there is because md5_match is inaccurate when there is no md5 header. The md5s did not match in that case, the test is just not applicable. What do you think?

Also it's not critical, but I usually prefer refactorings be separate from adding features.

**Comment by andres99x** [comment]
While working with Angular i run into a strange problem regarding `Content-Type`, angular returned `application/json;charset=utf-8` as my request's Content-Type but as soon as that request left the browser my `Content-Type` changed to `application/json;charset=UTF-8` (notice UTF-8 in uppercase).

So since i had this problem i thought it might be good to accept some custom headers for more flexibility and just in case something arises in the future, that's why i added them.

Oh now i see why you were using negative terminology, i usually prefer positive over negative because it's more natural and easier to understand but it's up to you.

Let's wait for @mgomes thoughts.

**Comment by kjg** [comment]
In the interest of time and actually moving forward with some of these changes, do you mind doing the refactoring as a separate PR, and only adding the new DATE header? I'm not too concerned with the capitalization of the charset, that's probably just the browser doing some normalization. I'd rather be more conservative and leave out the other headers until we know they are needed. We definitely know the DATE one is needed. Also let's leave it has mistmatch for now. We can also revisit that in a separate PR if needed.

**Comment by kjg** [comment]
I just merged in support for a new adapter which unfortunately makes this branch conflict now. I'd love to get the X-HMAC-DATE merged in, do you think you'll have a chance to work on these changes soon? Sorry for the extra work!

**Comment by bilby91** [comment]
@kjg Do you think we can merge this PR after fixing the conflicts ?

**Comment by kjg** [comment]
@bilby91 There were a couple of things I'd like to see changed. I'd like the refactorings to be separate from the functional changes. I'd also like this to be just for X-HMAC-DATE unless someone has actually run into a need for the other headers added here, and I wanted to leave the terminology as md5_mismatch for that feature. I'm guessing @andres99x no longer has the time to work on this, but if you'd like to make these changes in a new pull request, I'd love that and will definitely accept those changes.

**Comment by bilby91** [comment]
Cool. Let me see if we have some time with @andres99x to pull up the needed
changes.

Thanks!

Martín

@bilby91

**Pull request closed without merging**
