### PR TITLE
Add http.rb request driver

### PR DESCRIPTION
**Pull request by tycooon**
For https://github.com/httprb/http gem.

### CODE REVIEW

**Comment by fwininger** [comment]
Looks good to me.

**Comment by tycooon** [comment]
I added specs for different HTTP gem versions, please take a look.

**Comment by fwininger** [comment]
Seems to be good. 
@mgomes don't forget to squash all the commit then you merge.

**Comment by tycooon** [comment]
@mgomes would be really cool to get this merged!

**Comment by mgomes** [comment]
@tycooon sorry for the delay in getting this one merged. Really appreciate your contribution, though. I am going to roll out version `2.2.0` after merging this in.

**Comment by tycooon** [comment]
@mgomes I see you released version 2.2.0 on rubygems but it doesn't include this PR for some reason.

**Comment by mgomes** [comment]
@tycooon sorry about that. Looks like I bungled the release. Please give 2.2.1 a go.

**Pull request merged**
