### PR TITLE
Forward options in ActiveResource

### PR DESCRIPTION
**Pull request by fwininger**
Hi, I try to use ApiAuth with ActiveResource.
I saw that the options param is currently not forward to the sign! method.
This pull request fix it !

### CODE REVIEW

**Comment by fwininger** [comment]
up? @kjg

**Comment by kjg** [comment]
Thanks so much for this. What do you think about renaming the class attribute to something like `api_auth_options`. I just worry that adding `options` as a class method to ActiveResource::Base inherited classes might conflict with other uses.

**Comment by fwininger** [comment]
Hello @kjg, could you consider this merge request.
Thanks from France :)

**Comment by kjg** [comment]
Thanks! Sorry for the delay. I really wish github notified about new commits on a PR after a comment.

**Comment by fwininger** [comment]
Thanks

**Pull request merged**
