### PR TITLE
add new 'headers_to_sign' option to sign custom headers

### PR DESCRIPTION
**Pull request by fakenine**
Hello,

This adds the possibility to sign custom/specified headers via a headers_to_sign
option that will be passed as an array containing the headers names

To add more context into this, we would like to be able to sign the `X-Forwarded-For` header for instance

### CODE REVIEW

**Comment by fwininger** [comment]
Hi @fakenine, I think this PR can be very useful 👍 

Can you just do some tests and ensure that all current tests work ?

**Comment by fakenine** [comment]
Hello, I've added tests for this feature but I'm having trouble with an error on some pipelines, that I'm also seeing on other PRs

```
Failure/Error: require 'active_resource'
LoadError:
  cannot load such file -- rails
```

**Comment by fwininger** [comment]
Hi @fakenine, can you run rubocop and fix the issue ?

**Comment by fakenine** [comment]
Done!

**Pull request merged**
