### PR TITLE
Add PATCH request type via copy-paste

### PR DESCRIPTION
**Pull request by am-dmr**
Hi!

In most of cases a PATCH request is similar to POST/PUT. And like POST/PUT, PATCH should carry data in request body. So, MD5 populate/check must be default behavior for PATCH requests.

### CODE REVIEW

**Comment by mgomes** [comment]
@am-dmr thanks for PR! Could you get the tests green when you get a chance? I'd love to get this merged in.

**Comment by am-dmr** [comment]
@mgomes ok. I've forgot tests with rails 2.

**Comment by fwininger** [comment]
@am-dmr sounds good ! 

@mgomes, I think a better way is to accept the PR to remove Rails 2 and don't add more exceptions in the code to support old rubies.

**Comment by am-dmr** [comment]
@fwininger
I think that removing rails-2 and/or ruby-1.8 should bump version to 3.x.x

**Comment by fwininger** [comment]
@am-dmr, we work already on this #141

**Comment by am-dmr** [comment]
@mgomes 
I fixed code for rails 2. https://travis-ci.org/mgomes/api_auth/builds/219456687.
But I think, that https://travis-ci.org/mgomes/api_auth/jobs/219456716 is impossible, because there is no %i() in ruby < 2.0.

**Pull request closed without merging**
